<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make('Illuminate\Contracts\Console\Kernel');
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

// Lesson 77: Les lois de Newton
DB::table('lecons')->where('id', 77)->update([
    'contenu' => "# Les Lois de Newton\n\n## 1. Introduction\n\nIsaac Newton (1643-1727) a formulé les trois lois fondamentales du mouvement qui régissent la mécanique classique.\n\n## 2. Première Loi : Principe d'Inertie\n\n**Énoncé :** Un objet au repos reste au repos, et un objet en mouvement continue en mouvement rectiligne uniforme, sauf si une force extérieure agit sur lui.\n\n### Exemples :\n- 🚗 Passager projeté vers l'avant lors d'un freinage brusque\n- 🏀 La balle continue de rouler jusqu'à ce que la friction l'arrête\n- 🛸 Sonde spatiale continue sans moteur dans le vide\n\n### Formule :\nSi ΣF = 0, alors v = constante\n\n## 3. Deuxième Loi : F = m·a\n\n**Énoncé :** La force appliquée à un objet est égale à sa masse multipliée par son accélération.\n\n### Formule :\n**F = m × a**\n\nOù :\n- **F** : Force (Newtons, N)\n- **m** : Masse (kilogrammes, kg)\n- **a** : Accélération (m/s²)\n\n### Exemples :\n\n**Exemple 1 :**\nUne force de 10 N est appliquée à un objet de 2 kg. Quelle est l'accélération ?\n\n```\na = F / m = 10 / 2 = 5 m/s²\n```\n\n**Exemple 2 :**\nQuelle force faut-il pour accélérer une voiture de 1000 kg à 3 m/s² ?\n\n```\nF = m × a = 1000 × 3 = 3000 N\n```\n\n## 4. Troisième Loi : Action-Réaction\n\n**Énoncé :** Pour chaque action, il y a une réaction égale et opposée.\n\n### Exemples :\n- 🚀 Fusée : Les gaz poussés vers le bas propulsent la fusée vers le haut\n- 🚶 Marche : On pousse le sol vers l'arrière, le sol nous pousse vers l'avant\n- 🏊 Natation : On pousse l'eau vers l'arrière, l'eau nous pousse vers l'avant\n\n### Formule :\nF(action) = -F(réaction)\n\n## 5. Applications Pratiques\n\n### Chute Libre\nUn objet en chute libre subit uniquement la gravité :\n```\nF = m × g\noù g = 9.81 m/s² (accélération de la pesanteur)\n```\n\n### Plan Incliné\nDécomposer les forces :\n- Poids (P = m·g) vers le bas\n- Force normale perpendiculaire au plan\n- Friction opposée au mouvement\n\n## 6. Résumé des Trois Lois\n\n| Loi | Nom | Formule | Signification |\n|-----|-----|---------|---------------|\n| 1ère | Inertie | Si F=0, v=cste | Résistance au changement |\n| 2ème | Dynamique | F = m·a | Relation force-accélération |\n| 3ème | Action-Réaction | F₁ = -F₂ | Forces par paires |\n\n## Points Clés\n\n📌 La **1ère loi** explique l'inertie\n📌 La **2ème loi** : F = m·a (la plus utilisée)\n📌 La **3ème loi** : Les forces vont toujours par paires\n📌 Ces lois s'appliquent dans un référentiel galiléen"
]);

echo "✅ Leçon 77 (Lois de Newton) mise à jour\n";

// Lesson 78: Cinématique
DB::table('lecons')->where('id', 78)->update([
    'contenu' => "# Cinématique\n\n## 1. Qu'est-ce que la Cinématique ?\n\nLa **cinématique** est l'étude du mouvement des objets sans considérer les forces qui les provoquent.\n\n## 2. Grandeurs Fondamentales\n\n### Position (x)\nLieu où se trouve l'objet à un instant donné.\n\n### Vitesse (v)\nTaux de changement de la position.\n\n**Vitesse moyenne :**\n```\nv = Δx / Δt = (x₂ - x₁) / (t₂ - t₁)\n```\n\n**Vitesse instantanée :**\n```\nv = dx/dt (dérivée de la position)\n```\n\n### Accélération (a)\nTaux de changement de la vitesse.\n\n**Accélération moyenne :**\n```\na = Δv / Δt = (v₂ - v₁) / (t₂ - t₁)\n```\n\n## 3. Types de Mouvement\n\n### Mouvement Rectiligne Uniforme (MRU)\nVitesse constante, accélération nulle.\n\n**Formules :**\n```\nx(t) = x₀ + v·t\nv = constante\na = 0\n```\n\n**Exemple :**\nUne voiture roule à 60 km/h sur une route droite.\n\n### Mouvement Rectiligne Uniformément Accéléré (MRUA)\nAccélération constante.\n\n**Formules :**\n```\nv(t) = v₀ + a·t\nx(t) = x₀ + v₀·t + (1/2)·a·t²\nv² = v₀² + 2·a·Δx\n```\n\n**Exemple :**\nChute libre d'un objet (a = g = 9.81 m/s²)\n\n## 4. Exemples Résolus\n\n### Exemple 1 : MRU\nUne voiture roule à 20 m/s. Quelle distance parcourt-elle en 5 secondes ?\n\n```\nx = v × t = 20 × 5 = 100 m\n```\n\n### Exemple 2 : MRUA\nUn objet part du repos avec une accélération de 3 m/s². Quelle est sa vitesse après 4 secondes ?\n\n```\nv = v₀ + a·t = 0 + 3 × 4 = 12 m/s\n```\n\n### Exemple 3 : Chute Libre\nUn objet tombe d'une hauteur de 20 m. Combien de temps met-il pour toucher le sol ?\n\n```\nx = (1/2)·g·t²\n20 = (1/2) × 9.81 × t²\nt² = 20 / 4.905 = 4.08\nt = √4.08 ≈ 2.02 s\n```\n\n## 5. Représentation Graphique\n\n### Graphique Position-Temps\n- Pente = vitesse\n- Courbe = accélération\n\n### Graphique Vitesse-Temps\n- Pente = accélération\n- Aire sous la courbe = distance parcourue\n\n## 6. Mouvement Circulaire\n\n### Vitesse Angulaire (ω)\n```\nω = Δθ / Δt (en rad/s)\n```\n\n### Relation v = r·ω\n```\nv = r × ω\noù r = rayon du cercle\n```\n\n### Accélération Centripète\n```\nac = v² / r = r·ω²\n```\n\n## 7. Résumé des Formules\n\n### MRU\n- x = x₀ + v·t\n- v = constante\n\n### MRUA\n- v = v₀ + a·t\n- x = x₀ + v₀·t + (1/2)·a·t²\n- v² = v₀² + 2·a·Δx\n\n### Chute Libre\n- a = g = 9.81 m/s²\n\n## Points Clés\n\n📌 La cinématique décrit le **mouvement** sans les causes\n📌 **MRU** : vitesse constante\n📌 **MRUA** : accélération constante\n📌 Connaître les formules de base est essentiel"
]);

echo "✅ Leçon 78 (Cinématique) mise à jour\n";
