<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make('Illuminate\Contracts\Console\Kernel');
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

// Lesson 75: Introduction aux Bases de Données
DB::table('lecons')->where('id', 75)->update([
    'contenu' => "# Introduction aux Bases de Données\n\n## 1. Qu'est-ce qu'une Base de Données ?\n\nUne **base de données** est un ensemble structuré d'informations organisées pour être facilement accessibles.\n\n### Exemples :\n- 📱 Contacts du téléphone\n- 🛒 Catalogue e-commerce\n- 🎓 Dossiers étudiants\n\n## 2. Types de Bases de Données\n\n### Relationnelles (SQL)\nMySQL, PostgreSQL, SQLite - Données en tables\n\n### Non-Relationnelles (NoSQL)\nMongoDB, Redis - Formats flexibles\n\n## 3. Concepts Fondamentaux\n\n### Table\nReprésente une entité (ex: `etudiants`)\n\n| id | nom | email | age |\n|----|-----|-------|-----|\n| 1 | Ahmed | ahmed@email.com | 22 |\n| 2 | Fatima | fatima@email.com | 23 |\n\n### Clé Primaire (PRIMARY KEY)\nIdentifiant unique pour chaque enregistrement\n\n### Clé Étrangère (FOREIGN KEY)\nCrée un lien entre deux tables\n\n## 4. Relations entre Tables\n\n### Un-à-Plusieurs (1:N)\nUn enseignant → Plusieurs cours\n\n### Plusieurs-à-Plusieurs (N:M)\nÉtudiants ↔ Cours (via table `inscriptions`)\n\n## 5. Types de Données SQL\n\n- `INT` : Entier\n- `VARCHAR(100)` : Texte (max 100 caractères)\n- `TEXT` : Texte long\n- `DATE` : Date\n- `BOOLEAN` : Vrai/Faux\n\n## 6. Créer une Base et une Table\n\n```sql\nCREATE DATABASE universite;\nUSE universite;\n\nCREATE TABLE etudiants (\n    id INT PRIMARY KEY AUTO_INCREMENT,\n    nom VARCHAR(100) NOT NULL,\n    email VARCHAR(150) UNIQUE,\n    age INT\n);\n```\n\n## 7. Normalisation\n\nOrganiser les données pour réduire la redondance :\n- **1NF** : Valeurs atomiques\n- **2NF** : Dépendance de la clé primaire\n- **3NF** : Pas de dépendance transitive\n\n## SGBD Populaires\n\n- **MySQL/MariaDB** : Gratuit, populaire pour le web\n- **PostgreSQL** : Puissant, conforme aux standards\n- **SQLite** : Léger, parfait pour mobile\n\n## Points Clés\n\n📌 Les bases organisent les données en **tables**\n📌 Les **clés étrangères** relient les tables\n📌 **SQL** est le langage standard\n📌 La **normalisation** réduit la redondance"
]);

echo "✅ Leçon 75 (Bases de données) mise à jour\n";

// Lesson 76: Langage SQL
DB::table('lecons')->where('id', 76)->update([
    'contenu' => "# Langage SQL\n\n## 1. Qu'est-ce que SQL ?\n\n**SQL** (Structured Query Language) permet de communiquer avec les bases de données.\n\n## 2. Commandes Principales\n\n### SELECT - Lire des données\n```sql\n-- Tous les étudiants\nSELECT * FROM etudiants;\n\n-- Colonnes spécifiques\nSELECT nom, email FROM etudiants;\n\n-- Avec condition\nSELECT * FROM etudiants WHERE age > 20;\n\n-- Tri\nSELECT * FROM etudiants ORDER BY nom ASC;\n\n-- Limite\nSELECT * FROM etudiants LIMIT 10;\n```\n\n### INSERT - Insérer\n```sql\nINSERT INTO etudiants (nom, email, age)\nVALUES ('Benali', 'benali@email.com', 22);\n```\n\n### UPDATE - Modifier\n```sql\nUPDATE etudiants\nSET age = 23\nWHERE nom = 'Benali';\n```\n\n### DELETE - Supprimer\n```sql\nDELETE FROM etudiants WHERE id = 5;\n```\n\n## 3. Clauses Avancées\n\n### WHERE avec Opérateurs\n```sql\nWHERE age >= 18 AND age <= 25\nWHERE ville = 'Alger' OR ville = 'Oran'\nWHERE age IN (20, 21, 22)\nWHERE nom LIKE 'A%'\n```\n\n### COUNT, SUM, AVG\n```sql\nSELECT COUNT(*) FROM etudiants;\nSELECT AVG(age) FROM etudiants;\nSELECT MAX(age), MIN(age) FROM etudiants;\n```\n\n### GROUP BY\n```sql\nSELECT ville, COUNT(*) \nFROM etudiants \nGROUP BY ville;\n```\n\n### JOIN - Joindre des Tables\n```sql\nSELECT e.nom, c.titre\nFROM etudiants e\nJOIN inscriptions i ON e.id = i.etudiant_id\nJOIN cours c ON i.cours_id = c.id;\n```\n\n## 4. Créer une Table\n\n```sql\nCREATE TABLE cours (\n    id INT PRIMARY KEY AUTO_INCREMENT,\n    titre VARCHAR(200) NOT NULL,\n    credits INT DEFAULT 3\n);\n```\n\n## 5. Modifier une Table\n\n```sql\n-- Ajouter une colonne\nALTER TABLE etudiants ADD telephone VARCHAR(20);\n\n-- Supprimer une colonne\nALTER TABLE etudiants DROP COLUMN telephone;\n```\n\n## Bonnes Pratiques\n\n✅ Utiliser des requêtes préparées contre les injections SQL\n✅ Indexer les colonnes recherchées fréquemment\n✅ Utiliser LIMIT pour limiter les résultats\n✅ Toujours avoir une clause WHERE pour UPDATE/DELETE\n\n## Points Clés\n\n📌 **SELECT** pour lire\n📌 **INSERT** pour ajouter\n📌 **UPDATE** pour modifier\n📌 **DELETE** pour supprimer\n📌 **JOIN** pour combiner des tables"
]);

echo "✅ Leçon 76 (SQL) mise à jour\n";
